### ISSUE TITLE
Error when installed

### ISSUE THREAD

**Issue by nongbaoting** [sarahpyfrom/PLAIDOH#3]
```
-> % perl PLAIDOH.pl --cellENH A549 --cellSE A549 --cellCHIP A549 --RBP NONO Example_Input_File.txt
Experimental keys on scalar is now forbidden at PLAIDOH.pl line 378.
Type of arg 1 to keys must be hash or array (not hash element) at PLAIDOH.pl line 378, near "})"
Execution of PLAIDOH.pl aborted due to compilation errors.
```

I was encountered this error above when trying to install. I was wonder this was caused by Perl version inconsistent. Would you like to tell me which version of Perl did you use? And my Perl is version 5.26.1

**Comment by jannahshamsani** [comment]
I've got the same isssue. Did you manage to solve it?

**Comment by jannahshamsani** [comment]
simply changing line 278 to  `foreach my $key2 (keys %{$CHIA{$key}}){` works for me

**Comment by sarahpyfrom** [comment]
My apologies for letting this issue go unresolved for so long, @nongbaoting . I have updated the PLAIDOH.pl file as @jannahshamsani suggested above.
